sudo: required
services:
  - docker

before_install:
  - docker build -t terenian/docker-react .
script:
  - docker run -e CI=true terenian/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react-udemy"
  env: "DockerReactUdemy-env"
  bucket_name: "elasticbeanstalk-eu-west-3-465065747217"
  bucket_path: "docker-react-udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
language: generic
