udo: required
services:
  - docker

before_install:
  - docker build -t terenian/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true terenian/docker-react npm run test
language: generic
